apiVersion: batch/v1
kind: CronJob
metadata:
  name: oci-cf-ip-rule
  namespace: default
spec:
  schedule: '0 0 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 1000
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          containers:
            - name: oci-cf-ip-rule
              image: ghcr.io/powerkernel/oci-cf-ip-rule:v1.0.1
              imagePullPolicy: Always
              envFrom: # create your env config map
                - configMapRef:
                    name: oci-cf-ip-rule-env
              volumeMounts:
                - name: oci-api-key # create your oci-api-key secert
                  mountPath: /app/.oci/oci_api_key.pem
                  subPath: oci_api_key.pem
                - name: oci-api-auth # create your oci-api-auth config map
                  mountPath: /app/.oci/oci_api_key_public.pem
                  subPath: oci_api_key_public.pem
                - name: oci-api-auth
                  mountPath: /app/.oci/config
                  subPath: config
          volumes:
            - name: oci-api-auth
              configMap:
                name: oci-api-auth
            - name: oci-api-key
              secret:
                secretName: oci-api-key-cred
